[build]
  publish = "dist"  # or "public" depending on your build output
  command = "npm run build"  # or your build command

[build.environment]
  NODE_VERSION = "18"  # or whatever version you're using 